### ISSUE TITLE
Duplicate note names overwrites previous note with no warning!

### ISSUE THREAD

**Issue by TechGuyAlabama** [cu/silicon#10]
I did notice one thing, if you have a note named "test1" created and create a new note and call it "test1", there is no warning, it just overwrites the previous note. Could end up causing issues with notes that go missing.

Great job btw!

**Comment by TheNomad11** [comment]
Didn't you want to post it there https://github.com/kyoheiu/carbon I saw your post here @TechGuyAlabama https://old.reddit.com/r/selfhosted/comments/16cav8c/carbon_an_opinionated_online_text_editor/

**Comment by TechGuyAlabama** [comment]
um oops sry :D

Too many windows open.

**Comment by TechGuyAlabama** [comment]
Wrong project, my bad.
